#!/usr/bin/env python3
'''Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
'''

def fib_seq(num):
    '''Calculate the nth term of the Fibonacci sequence where n is num'''
    if (num <= 1):
        return num
    else:
        return fib_seq(num - 1) + fib_seq(num - 2)

total = 0
i = 2
curr = fib_seq(i)
not_exceed = 4000000

while (curr < not_exceed):
    if curr % 2 == 0:
        total += curr
    i += 1
    curr = fib_seq(i)

print(total)

